[package]
name = "application"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
staticizer = { path = "../../.." }
base = { path = "../base" }
library = { path = "../library" }
versioned_one = { package = "versioned", path = "../versioned-1" }
versioned_two = { package = "versioned", path = "../versioned-2" }
