[package]
name = "staticizer"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Collect typed Rust metadata and construct static data during compilation"

[workspace]
members = ["macros"]
default-members = [".", "macros"]
resolver = "3"

[dependencies]
staticizer-macros = { path = "macros", version = "0.1.0" }
