[package]
name = "staticizer-macros"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Registration attribute for staticizer"
repository = "https://github.com/da-shalev/staticizer"
keywords = ["const", "compile-time", "registry", "staticizer"]
categories = ["development-tools::procedural-macro-helpers"]
include = ["/src", "/LICENSE"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
